version: '3.8'
services:
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    hostname: "db"
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beteclic

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - '8080:8080'

  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    volumes:
      - './public:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '8000:80'
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './:/usr/src/app'
    restart: on-failure
    env_file:
      - .env
    user: 1000:1000